name: tez_med_client
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+20

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.8.0
  auto_route: ^9.2.2
  dio: ^5.7.0
  synchronized: ^3.3.0+3
  shared_preferences: ^2.3.2
  hive_flutter: ^1.1.0
  get_it: ^8.0.2
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.4
  equatable: ^2.0.5
  url_launcher: ^6.3.1
  flutter_multi_formatter: ^2.13.0
  pinput: ^5.0.0
  geolocator: ^13.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  yandex_mapkit: ^4.1.0
  lottie: ^3.1.3
  skeletonizer: ^1.4.2
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  firebase_core: ^3.8.0
  flutter_markdown: ^0.7.4+1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  geocoding: ^3.0.0
  sms_autofill: ^2.4.1
  package_info_plus: ^8.1.1
  device_info_plus: ^11.2.0
  in_app_update: ^4.2.3
  http_parser: ^4.1.2
  file_picker: ^8.1.7
  in_app_review: ^2.0.10
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.4
  chuck_interceptor: ^2.2.3
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.4.0
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.7.0
  icons_launcher: ^3.0.0
  change_app_package_name: ^1.4.0
  hive_generator: ^2.0.1

flutter_gen:
  output: lib/gen/
  line_length: 90

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/pirvacy_policy/


icons_launcher:
  image_path: "assets/logo/app_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter_native_splash:
  color: "#ffffff" 
  image: assets/images/ic_launcher-playstore.png  
  android_12:
    image: assets/images/ic_launcher-playstore.png
    icon_background_color: "#ffffff"
  fullscreen: true
